# Generated by Django 5.0.6 on 2024-07-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.TextField()),
                ('cuisine', models.CharField(max_length=255)),
                ('meal', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('spice_level', models.CharField(max_length=255)),
                ('dietary_preference', models.CharField(max_length=255)),
                ('allergies', models.CharField(max_length=255)),
                ('nutrition_goals', models.TextField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
